version: '2'
services:
  db:
    image: imiell/sqlite
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "9090:9090"
    depends_on:
      - db
