# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destinationLocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='locations.Location')),
                ('sourceLocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_location', to='locations.Location')),
            ],
        ),
    ]
