# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20161106_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direction',
            old_name='destinationLocation',
            new_name='destination_location',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='sourceLocation',
            new_name='source_location',
        ),
    ]
