# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20161106_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_location', to='locations.Location'),
        ),
    ]
